### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [brycerohrer/reddit_video_maker#5]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by alexshelto** [comment]
Thanks for the suggestion! I will get on that ASAP :)

**Comment by TechnologyClassroom** [comment]
Let me know if you need help.

**Comment by alexshelto** [comment]
Thanks currently I am exploring options for different Licenses

**Comment by TechnologyClassroom** [comment]
I would recommend the GPL licenses because permissive licenses (MIT, Apache, BSD, etc.) tend to have proprietary forks.  If a fork is proprietary, the upstream project never gets the opportunity to benefit from those changes.

**Comment by alexshelto** [comment]
I am trying to add a GPL license to the repo. I am adding new file, `License.md` but there are no GPL licenses that pop up for me to select.

**Comment by alexshelto** [comment]
@TechnologyClassroom Can you confirm I have added the correct GPL license?
Found from: https://github.com/KSXGitHub/GPL-3.0/blob/master/LICENSE

**Comment by TechnologyClassroom** [comment]
@alexshelto [LICENSE.md](https://github.com/brycerohrer/reddit_video_maker/blob/main/LICENSE.md) looks right!
