### ISSUE TITLE
AttributeError: module 'config' has no attribute 'PRAW_CONFIG'

### ISSUE THREAD

**Issue by RealStJimmy** [brycerohrer/reddit_video_maker#6]
I'm really confused on what the config.py file is supposed to look like. Can you give an example one?

**Comment by alexshelto** [comment]
Will update repo with a demo config file and add to README. 
Example config file: located in src/ directory goes as shown: 

```
PRAW_CONFIG = {
    'client_id': '',
    'client_secret': '',
    'user_agent': 'user-agent'
    }
```
the user agent can be the same as thats the default, see: https://www.reddit.com/prefs/apps and https://www.jcchouinard.com/get-reddit-api-credentials-with-praw/ for help creating a Praw 'app' and acquiring credentials. 

Let me know if this helps :)

**Comment by alexshelto** [comment]
I have updated the repo with an example PRAW_CONFIG object and file. Closing issue.
